version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
  commands:
   - python3 -m venv venv
   - . venv/bin/activate
   - pip install -r ./src/requirements.txt
 build: 
  commands:
   - sam build
   - export BUCKET=test-pipeline-output-bucket12345
   - export SAM_CLI_TELEMETRY=0
   - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
environment:
  variables:
    SAM_CLI_TELEMETRY: "0"
artifacts:
 type: zip
 files:
  - template.yml
  - outputtemplate.yml